apiVersion: apps/v1
kind: Deployment
metadata:
  name: moscow-time
  labels:
    app: moscow-time
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moscow-time
  template:
    metadata:
      labels:
        app: moscow-time
    spec:
      containers:
      - name: moscow-time
        image: shuvani/moscow_time:12.4.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
