apiVersion: apps/v1
kind: Deployment
metadata:
  name: moscow-time
  labels:
    app: moscow-time
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moscow-time
  template:
    metadata:
      labels:
        app: moscow-time
    spec:
      containers:
      - name: moscow-time
        image: shuvani/moscow_time:10.0.0
        ports:
        - containerPort: 8000
