---
- name: Create directory
  file:
    path: "{{ deploy_image_path }}"
    state: directory
    mode: '0755'

- name: Copy docker-compose
  ansible.builtin.copy:
    src: templates/docker-compose.yml
    dest: "{{ deploy_image_path }}"
    mode: '0755'

- name: Run docker-compose up
  community.docker.docker_compose:
    project_src: "{{ deploy_image_path }}"
    build: false
  register: output
