name: Redeploy moscow time project

on:
  push:
    branches:
      - 'release-*'

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-20.04
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
    - uses: actions/checkout@v2
    - name: Set variables
      env:
        VERSION: $(sed -n 's/version=//p' setup.py | sed 's/"//' | sed 's/",//g')
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USER }}
          -p ${{ secrets.DOCKER_PASS }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: app_python/
        push: true
        tags: ${{ secrets.DOCKER_USER }}/moscow_time:$VERSION