name: Redeploy moscow time project
author: Anna Gorb
description: This action deploys the application in the docker

on:
  push:
    branches:
      - 'release-*'

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-20.04
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USER }}
          -p ${{ secrets.DOCKER_PASS }}
    - name: Build Docker image
      run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
    - name: Publish Docker image
      run: docker push $REPO